version: '3.5'

services:
        carbon:
           container_name: carbonpredict
           image: carbon
           ports:
             - "5000:5000"
           volumes:
             - ./mnt_models:/usr/app/mnt
             - ./mnt_emission_data:/emission_data
             - ./mnt_results:/results